//
//  QRCode8BitTest.swift
//  QRCode GeneratorTests
//
//  Created by Vitali Kurlovich on 11/13/17.
//  Copyright © 2017 Vitali Kurlovich. All rights reserved.
//

import XCTest

@testable import QRCode

class QRCode8BitTests: XCTestCase {
	
	func testQRCode8Bi_SHA3_384 () throws {
		
		var qr = try QRCode("0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004")
		
		XCTAssertEqualMultiarray(
			qr.modules,	[[true ,true ,true ,true ,true ,true ,true ,false,false,true ,true ,false,true ,false,false,true ,false,false,false,false,false,true ,false,true ,false,true ,false,true ,true ,false,false,true ,false,false,true ,false,true ,true ,false,false,false,false,true ,false,false,false,true ,true ,true ,true ,true ,true ,true ],
							[true ,false,false,false,false,false,true ,false,false,true ,false,false,true ,true ,true ,false,true ,true ,true ,true ,true ,false,false,false,false,true ,false,true ,false,false,true ,true ,false,false,false,true ,false,false,false,true ,false,true ,true ,true ,false,false,true ,false,false,false,false,false,true ],
							[true ,false,true ,true ,true ,false,true ,false,false,true ,true ,false,false,true ,true ,false,false,false,false,false,false,false,true ,true ,false,false,false,true ,false,false,false,false,false,false,true ,true ,false,false,false,true ,false,false,false,true ,false,false,true ,false,true ,true ,true ,false,true ],
							[true ,false,true ,true ,true ,false,true ,false,false,false,true ,true ,false,true ,false,true ,true ,false,false,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,true ,false,false,false,true ,false,false,true ,false,false,true ,false,true ,false,true ,false,true ,true ,true ,false,true ],
							[true ,false,true ,true ,true ,false,true ,false,true ,false,false,false,true ,true ,true ,true ,false,true ,false,true ,false,false,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,false,false,true ,true ,false,false,false,true ,false,false,false,true ,false,true ,true ,true ,false,true ],
							[true ,false,false,false,false,false,true ,false,false,false,false,false,false,true ,true ,true ,false,true ,true ,true ,true ,false,false,true ,true ,false,false,false,true ,false,true ,false,true ,false,true ,false,false,true ,true ,false,true ,true ,true ,false,false,false,true ,false,false,false,false,false,true ],
							[true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ],
							[false,false,false,false,false,false,false,false,true ,true ,false,false,false,true ,false,false,true ,true ,false,false,true ,false,false,false,true ,false,false,false,true ,false,true ,true ,false,true ,false,false,true ,false,true ,true ,true ,true ,false,false,true ,false,false,false,false,false,false,false,false],
							[false,false,true ,true ,false,false,true ,true ,true ,false,true ,false,false,true ,false,false,false,false,false,false,true ,true ,false,false,true ,true ,true ,true ,true ,true ,true ,true ,false,false,true ,false,false,true ,true ,false,true ,false,true ,false,true ,true ,true ,false,true ,false,false,false,false],
							[false,false,true ,true ,true ,false,false,false,true ,true ,true ,true ,true ,true ,true ,false,true ,false,false,false,true ,false,false,false,true ,true ,true ,false,false,false,false,true ,false,false,true ,false,true ,true ,false,true ,true ,false,true ,false,false,false,false,true ,true ,false,false,false,true ],
							[true ,true ,true ,false,false,false,true ,false,false,false,true ,false,false,true ,true ,true ,true ,true ,false,false,false,true ,true ,false,false,false,false,true ,true ,true ,true ,true ,false,false,false,false,false,false,false,false,false,false,true ,true ,true ,false,true ,true ,false,true ,true ,false,false],
							[true ,false,true ,false,false,true ,false,false,true ,true ,false,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,true ,true ,false,true ,true ,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,false,true ,false,false,false,true ,false,true ,true ,false,true ,true ,false,true ,true ],
							[false,true ,false,false,false,true ,true ,true ,false,false,true ,false,true ,true ,false,false,true ,false,true ,false,false,false,true ,true ,false,true ,true ,true ,false,true ,false,true ,false,false,true ,false,true ,true ,true ,true ,false,true ,true ,true ,true ,false,false,true ,true ,true ,true ,false,false],
							[false,true ,true ,false,true ,true ,false,false,false,true ,true ,false,true ,true ,false,false,true ,false,true ,true ,true ,true ,false,true ,false,true ,true ,false,true ,false,false,false,true ,false,true ,false,false,false,true ,false,false,false,false,false,true ,false,false,true ,true ,false,true ,true ,true ],
							[false,false,true ,true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,false,false,true ,true ,false,true ,true ,false,true ,false,true ,true ,false,false,false,false,true ,false,true ,false,true ,true ,false,true ,false,false,false,false,false,false,true ],
							[false,false,false,true ,true ,false,false,false,true ,false,false,false,true ,true ,true ,true ,false,false,true ,false,true ,true ,false,false,false,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,false,false,true ,true ,true ,true ,true ,false,false,false,true ,false,false,false,false,false],
							[true ,true ,false,true ,false,true ,true ,false,true ,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,true ,false,true ,true ,false,false,false,false,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,false,true ,true ,false,false,true ,true ,false,true ,false,true ,false],
							[false,false,true ,true ,true ,false,false,false,false,false,true ,true ,true ,true ,true ,true ,false,true ,false,true ,true ,false,true ,true ,true ,false,true ,false,false,false,false,true ,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ,false,false,true ,true ,false,true ,false,true ,false],
							[false,true ,true ,false,true ,true ,true ,true ,true ,false,true ,false,false,true ,false,false,false,true ,false,false,true ,true ,true ,false,false,true ,true ,true ,false,true ,true ,false,false,true ,false,false,false,true ,true ,false,false,true ,false,false,true ,false,true ,false,false,true ,true ,true ,false],
							[true ,false,false,true ,true ,false,false,true ,false,true ,true ,false,false,false,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,false,true ,true ,true ,true ,false,false,true ,true ,false,true ,true ,true ,true ,false,false],
							[false,false,true ,true ,false,false,true ,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,true ,false,false,false,false,false,false,true ,true ,true ,true ,true ,false,false,true ,true ,true ,false,true ,true ,false,true ,false,true ,true ,false,true ],
							[false,false,true ,true ,true ,false,false,false,false,false,false,false,false,true ,false,false,false,false,false,false,true ,false,true ,true ,false,true ,true ,false,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,false,false,true ,false,false,false,false,false,true ,true ,false,true ,true ],
							[false,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,true ,true ,false,false,true ,true ,false,false,false,false,true ,true ,false,false,true ,true ,false,false,false,true ,false],
							[false,true ,true ,true ,false,false,false,true ,false,false,false,true ,false,false,true ,false,true ,true ,false,false,false,true ,false,false,true ,false,false,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,false,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,true ,true ],
							[false,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,false,false,true ,false,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false],
							[false,false,false,false,true ,false,false,false,true ,false,false,true ,false,false,true ,false,true ,true ,true ,false,false,false,false,false,true ,false,false,false,true ,false,false,true ,false,false,true ,true ,true ,false,true ,false,true ,true ,false,true ,true ,false,false,false,true ,true ,true ,true ,true ],
							[true ,false,false,false,true ,false,true ,false,true ,true ,false,true ,true ,false,false,true ,false,true ,false,false,false,true ,false,true ,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,true ,true ,false,true ,false,true ,false,false,false,true ],
							[false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,false,false,true ,true ,false,true ,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,false,true ,true ,false,false,true ,false,true ,false,false,true ,true ,true ,false,true ,false,false,false,true ,false,false,true ,true ],
							[false,true ,true ,false,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,false,true ,false,false,false,false,false,true ,true ,true ,true ,true ,true ,true ,false,false,false],
							[false,true ,true ,false,false,true ,false,true ,false,true ,false,false,false,false,false,false,false,false,false,false,false,false,true ,true ,true ,true ,false,false,true ,true ,true ,true ,false,true ,false,true ,true ,false,false,true ,true ,true ,false,true ,true ,false,true ,false,false,true ,false,true ,false],
							[false,true ,false,false,true ,false,true ,false,false,true ,true ,true ,false,true ,true ,true ,true ,false,true ,true ,false,false,false,false,true ,true ,false,false,true ,true ,true ,false,false,true ,false,false,true ,false,true ,true ,true ,false,false,false,false,false,false,true ,true ,false,false,true ,false],
							[false,false,false,false,true ,true ,false,false,false,true ,false,false,false,false,true ,false,false,false,true ,true ,false,false,false,true ,true ,false,true ,false,true ,true ,false,true ,false,false,false,false,true ,false,true ,true ,true ,false,false,true ,false,false,true ,false,false,true ,true ,false,false],
							[true ,false,true ,true ,false,true ,true ,false,true ,false,false,false,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,true ,false,true ,true ,true ,false,false,true ,true ,false,false,false,false,true ,false,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,true ,false,false],
							[false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,false,true ,false,false,true ,false,false,false,false,true ,false,true ,false,false,false,false,true ,true ,true ,true ,false,true ,true ,true ,true ,false,false,true ,false,false,true ,false,false,false,false,false,true ,true ,false,false,true ],
							[false,false,true ,false,false,true ,true ,false,false,false,false,true ,true ,true ,false,true ,false,true ,false,true ,false,false,false,false,true ,false,false,false,true ,true ,false,true ,false,true ,false,false,false,true ,false,false,true ,false,true ,false,false,true ,false,true ,true ,false,true ,false,false],
							[false,true ,true ,false,false,true ,false,false,false,true ,false,false,false,true ,true ,false,true ,false,false,false,true ,true ,false,false,false,false,false,true ,true ,true ,true ,false,true ,false,true ,true ,true ,false,false,true ,false,false,false,false,false,false,false,true ,false,false,false,false,false],
							[false,false,false,false,true ,false,true ,true ,true ,true ,true ,true ,false,false,true ,true ,true ,false,false,false,false,false,true ,true ,false,true ,true ,true ,false,false,true ,true ,true ,false,false,false,true ,false,true ,true ,false,true ,true ,false,true ,false,false,true ,false,false,true ,false,false],
							[true ,true ,true ,true ,true ,false,false,true ,false,false,false,false,true ,true ,true ,false,false,true ,true ,true ,false,false,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,false,true ,true ,false,true ,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ,false,false,true ,false,true ],
							[true ,true ,true ,false,false,true ,true ,true ,false,true ,true ,true ,true ,true ,false,true ,false,false,false,false,true ,true ,false,true ,true ,false,false,true ,false,true ,true ,false,true ,false,false,false,false,true ,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ],
							[false,false,true ,true ,false,false,false,true ,true ,true ,false,false,false,true ,true ,true ,true ,true ,false,false,false,false,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,false,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,true ,true ,false,true ,true ,false,false,false],
							[false,true ,true ,false,false,false,true ,false,false,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,true ,true ,true ,false,false,true ,true ,false,true ,false,true ,true ,false,false,true ,true ,false,true ,true ,true ,false,true ,false,false,true ,false,false,false,true ,false,false,false,false],
							[false,true ,false,false,false,true ,false,true ,false,false,true ,false,false,false,true ,true ,false,false,false,false,false,true ,true ,true ,false,true ,true ,false,true ,false,true ,false,false,false,false,true ,false,false,false,true ,true ,false,false,true ,true ,true ,true ,false,false,false,false,true ,false],
							[true ,true ,false,true ,true ,true ,true ,false,true ,true ,true ,true ,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,true ,true ,false,false,false,false,false,true ,true ,true ,false,true ,false,false,true ,false,false,false,false,false,false,true ,true ,false,true ,false],
							[false,true ,true ,false,false,false,false,true ,true ,false,false,true ,false,false,true ,true ,false,true ,false,false,false,false,true ,false,false,true ,false,false,true ,false,false,true ,false,false,false,false,true ,false,false,true ,true ,true ,false,true ,false,false,true ,true ,false,false,true ,false,false],
							[false,false,false,true ,false,false,true ,false,false,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,false,false,false,true ,true ,true ,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,false,true ,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,false],
							[false,false,false,false,false,false,false,false,true ,true ,true ,true ,false,false,true ,true ,false,true ,true ,true ,true ,false,false,false,true ,false,false,false,true ,false,false,false,false,false,true ,false,true ,false,false,true ,true ,false,true ,true ,true ,false,false,false,true ,false,true ,true ,true ],
							[true ,true ,true ,true ,true ,true ,true ,false,true ,false,false,false,true ,true ,true ,false,false,false,false,true ,false,true ,true ,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,false,false,true ,false,true ,false,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,false],
							[true ,false,false,false,false,false,true ,false,false,false,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,false,false,true ,true ,false,false,false,false,false,false,true ,true ,false,false,false,true ,true ,false,true ,true ],
							[true ,false,true ,true ,true ,false,true ,false,false,true ,false,true ,true ,false,true ,true ,false,false,false,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,true ,false,false,true ,false,false,false,true ,false,true ,false,false,true ,true ,false,true ,true ,true ,true ,true ,true ,true ,false,false],
							[true ,false,true ,true ,true ,false,true ,false,true ,true ,false,true ,false,false,true ,false,false,false,false,false,true ,false,false,true ,false,false,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,false,false,false,true ,false,true ,true ,false,true ,false,true ],
							[true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ,false,true ,false,false,false,true ,true ,false,true ,false,true ,false,true ,true ,true ,false,false,true ,false,true ,false,false,true ,false,true ,true ,true ,true ,false,true ,false,false,false,true ,true ,false,false,false,true ,true ],
							[true ,false,false,false,false,false,true ,false,false,false,true ,true ,false,false,false,false,false,true ,true ,false,false,false,false,false,true ,false,true ,false,true ,true ,false,false,true ,true ,true ,false,true ,true ,false,false,true ,true ,true ,false,false,false,false,false,true ,false,false,true ,false],
							[true ,true ,true ,true ,true ,true ,true ,false,false,true ,true ,true ,true ,true ,false,true ,true ,true ,false,true ,true ,false,false,true ,true ,false,true ,true ,true ,false,false,true ,false,true ,false,true ,false,false,true ,false,false,false,true ,false,false,false,true ,false,false,true ,false,true ,false]])
		
		
		
		
		print(String(qr))
		
		
		qr = try QRCode("0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004", .M)
		
		XCTAssertEqualMultiarray(
			qr.modules,
			[[true ,true ,true ,true ,true ,true ,true ,false,false,true ,false,true ,true ,true ,false,false,false,false,true ,true ,true ,false,true ,true ,true ,false,true ,false,false,false,false,true ,false,false,true ,true ,true ,true ,true ,true ,true ],
			 [true ,false,false,false,false,false,true ,false,false,true ,false,false,false,true ,false,false,false,false,true ,false,false,false,true ,false,false,false,false,true ,true ,false,false,false,true ,false,true ,false,false,false,false,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,false,false,false,true ,false,false,false,true ,false,false,false,true ,false,false,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,false,true ,false,false,true ,false,true ,false,true ,true ,true ,false,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,false,false,false,true ,false,false,false,false,false,true ,false,true ,false,true ,false,false,true ,false,true ,true ,false,true ,true ,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,false,false,false,false,true ,false,true ,false,true ,false,false,true ,false,true ,true ,false,false,false,true ,true ,false,false,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,false,false,false,false,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ],
			 [false,false,false,false,false,false,false,false,true ,false,false,true ,true ,false,false,false,true ,false,false,false,false,true ,true ,true ,false,false,false,true ,false,false,true ,false,false,false,false,false,false,false,false,false,false],
			 [true ,false,true ,true ,true ,true ,true ,false,false,true ,true ,false,false,true ,false,false,false,true ,true ,true ,true ,false,false,false,false,true ,false,true ,false,true ,true ,false,true ,false,true ,true ,true ,true ,true ,false,false],
			 [false,true ,true ,true ,false,true ,false,false,true ,true ,true ,true ,true ,true ,false,true ,true ,false,false,true ,false,true ,true ,true ,true ,false,true ,false,true ,false,false,true ,false,false,true ,false,true ,false,false,true ,true ],
			 [true ,false,false,true ,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,false,false,false,false,false,false,false,false,false,false,false,false,true ,false,false,true ,false,false,false,false,true ,true ,false,false,false,false],
			 [false,false,false,false,true ,false,false,true ,true ,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ,true ,false,true ,false,true ,true ,true ,false,false,true ,false,true ,false,true ,true ,true ,false,true ,true ],
			 [false,false,false,false,true ,false,true ,true ,true ,true ,true ,true ,false,true ,true ,false,false,true ,false,true ,false,false,false,false,false,true ,true ,true ,true ,true ,true ,false,true ,true ,false,true ,false,false,true ,false,false],
			 [true ,false,true ,false,true ,false,false,true ,false,true ,false,true ,false,false,true ,false,false,false,true ,false,true ,true ,true ,false,true ,false,false,false,false,false,false,true ,false,false,true ,false,true ,false,false,true ,true ],
			 [false,false,true ,true ,false,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ,true ,true ,false,false,false,false,false,false,false,true ,false,true ,true ,false,false,true ,false,false,true ,true ,true ,false,false],
			 [true ,true ,false,false,true ,true ,false,true ,false,true ,true ,true ,false,false,true ,false,true ,false,true ,true ,true ,true ,false,false,true ,false,true ,false,true ,false,true ,false,false,false,false,false,false,false,false,false,false],
			 [false,false,false,true ,false,true ,true ,false,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,true ,false,false,false,false,false,true ,false,true ,true ,true ,false,false,false,true ,false,false,false,true ,true ,true ,false],
			 [false,true ,true ,false,true ,false,false,false,false,true ,false,false,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,false,true ,true ,true ,true ,false,true ,true ,true ,false,false,true ,true ],
			 [true ,false,true ,false,true ,true ,true ,false,false,true ,true ,false,true ,true ,false,true ,false,true ,false,false,true ,true ,false,false,false,false,false,true ,true ,false,true ,false,true ,false,false,true ,false,false,true ,false,false],
			 [false,true ,true ,true ,false,false,false,false,true ,true ,false,false,false,false,false,true ,false,true ,true ,false,false,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,false,false,false,true ,true ,false,true ,false],
			 [false,false,false,false,true ,false,true ,true ,true ,false,false,true ,true ,false,false,false,false,false,false,false,true ,true ,false,false,true ,true ,false,true ,false,true ,false,false,true ,false,false,false,false,false,true ,false,false],
			 [false,false,true ,true ,false,false,false,false,true ,false,false,false,false,false,false,true ,true ,false,true ,true ,false,true ,true ,true ,false,false,true ,false,true ,false,true ,true ,false,true ,true ,true ,true ,false,false,false,true ],
			 [false,true ,false,false,true ,false,true ,true ,false,false,false,false,false,false,true ,false,true ,true ,true ,false,true ,true ,false,false,true ,true ,true ,true ,true ,false,false,false,true ,true ,true ,false,false,false,true ,true ,false],
			 [false,false,true ,true ,false,true ,false,true ,false,true ,false,false,true ,false,true ,false,false,false,true ,false,false,true ,false,false,false,false,true ,true ,false,false,true ,false,true ,false,false,false,true ,false,false,true ,false],
			 [true ,true ,false,false,false,false,true ,true ,false,false,true ,true ,true ,false,false,false,false,true ,false,true ,true ,false,false,false,false,true ,true ,true ,true ,true ,true ,false,false,true ,false,false,false,true ,true ,true ,false],
			 [false,true ,false,false,true ,true ,false,false,false,true ,true ,false,true ,false,true ,true ,true ,false,true ,true ,false,true ,true ,true ,true ,false,false,false,false,false,false,true ,true ,false,true ,true ,true ,false,false,true ,true ],
			 [true ,false,true ,true ,false,true ,true ,true ,true ,true ,false,true ,true ,true ,false,false,false,false,false,false,false,false,true ,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,true ,true ,true ,true ,false,false],
			 [true ,false,true ,false,true ,false,false,false,true ,false,false,false,true ,false,true ,false,false,false,false,false,true ,true ,false,false,true ,false,true ,true ,true ,false,false,false,true ,false,false,true ,true ,false,false,false,true ],
			 [false,true ,false,false,true ,false,true ,false,false,true ,false,true ,false,false,false,true ,true ,true ,true ,false,true ,false,false,false,true ,true ,false,true ,false,true ,true ,false,true ,false,false,true ,false,true ,true ,false,false],
			 [true ,true ,true ,true ,false,false,false,false,true ,false,false,true ,true ,true ,false,true ,true ,false,false,false,false,true ,true ,false,false,false,true ,false,true ,false,false,true ,false,true ,true ,false,true ,false,false,false,true ],
			 [true ,false,false,false,false,true ,true ,true ,false,false,true ,false,false,false,true ,false,true ,false,false,false,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,false,true ,false,false,false,true ,false,true ,true ,false],
			 [true ,false,true ,false,true ,false,false,false,false,true ,true ,true ,true ,true ,false,true ,true ,false,true ,false,false,true ,false,true ,false,false,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,false,false,false,true ],
			 [true ,false,false,false,false,true ,true ,true ,false,false,false,true ,true ,false,true ,true ,true ,true ,true ,false,false,false,false,true ,false,true ,false,true ,true ,true ,false,false,true ,true ,true ,true ,true ,true ,true ,false,false],
			 [false,false,false,false,false,false,false,false,true ,false,true ,false,true ,true ,false,false,true ,false,false,true ,true ,false,true ,true ,true ,false,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,false,false,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,false,true ,true ,false,false,true ,true ,true ,false,false,true ,false,false,false,true ,false,true ,false,true ,true ,true ,false,false,true ,true ,false,true ,false,true ,false,true ,true ,false],
			 [true ,false,false,false,false,false,true ,false,true ,false,false,true ,true ,true ,false,false,false,false,false,false,true ,false,false,false,true ,false,false,false,false,false,true ,false,true ,false,false,false,true ,true ,false,false,false],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,false,true ,true ,true ,true ,true ,true ,false,true ,false,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,false,true ,true ,true ,true ,true ,false,true ,false,false],
			 [true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,false,false,false,true ,false,false,false,false,true ,false,true ,false,true ,false,true ,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,false,true ,true ,false,true ,false,true ,false,false,false,true ,true ,false,false,false,false,true ,false,true ,false,true ,false,true ,false,false],
			 [true ,false,false,false,false,false,true ,false,false,false,false,true ,true ,false,false,true ,false,true ,true ,false,false,true ,true ,false,true ,false,false,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,true ,false],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,false,true ,true ,true ,false,true ,true ,false,false,false,true ,true ,false,true ,false,true ,false,true ,false,false,false,false,true ,true ,true ,false,true ,false,false]])
		
		print(String(qr))
		
		
		qr = try QRCode("0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004", .Q)
		XCTAssertEqualMultiarray(
			qr.modules,
			[[true ,true ,true ,true ,true ,true ,true ,false,false,false,true ,true ,false,false,true ,false,false,false,true ,false,true ,true ,true ,false,false,true ,true ,false,false,true ,true ,true ,false,true ,false,true ,false,false,false,false,true ,false,true ,true ,true ,true ,true ,true ,true ],
			 [true ,false,false,false,false,false,true ,false,true ,true ,true ,false,true ,false,false,true ,true ,true ,false,false,false,true ,false,true ,false,false,false,true ,false,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,false,true ,false,false,false,false,false,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,false,true ,false,true ,true ,false,true ,true ,false,false,false,false,false,false,true ,false,true ,false,false,false,false,true ,true ,false,false,false,true ,false,true ,false,false,true ,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,false,false,true ,false,false,false,false,true ,false,true ,true ,false,false,false,true ,true ,true ,true ,true ,false,true ,true ,false,false,false,false,false,true ,false,true ,false,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,false,false,false,false,true ,false,false,false,false,true ,true ,true ,false,false,true ,false,false,true ,true ,false,true ,false,false,false,true ,true ,false,true ,true ,false,false,true ,false,true ,false,false,true ,false,false,false,true ,false,false,false,false,false,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ],
			 [false,false,false,false,false,false,false,false,false,true ,true ,true ,true ,true ,false,false,true ,true ,false,true ,true ,true ,true ,false,false,false,true ,true ,false,true ,false,true ,true ,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],
			 [false,true ,true ,true ,false,true ,true ,false,false,true ,true ,false,true ,false,true ,true ,false,false,true ,false,false,true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,true ,false,false,true ,false,true ,false,false,false,false,false,false,true ,true ,false],
			 [true ,false,false,false,true ,false,false,false,false,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,false,false,false,false,false,false,true ,false,true ,true ,false,false,false,true ,true ,false,false,true ,false,true ,true ,true ,false,true ,false,false,false],
			 [false,true ,true ,false,true ,false,true ,false,false,true ,true ,false,false,true ,true ,false,true ,true ,false,false,false,false,false,false,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,false,false],
			 [false,false,false,false,false,false,false,false,true ,true ,false,false,false,true ,true ,false,false,true ,true ,false,true ,true ,false,true ,false,true ,true ,true ,true ,false,false,false,true ,false,true ,false,true ,true ,false,true ,true ,true ,false,true ,true ,false,true ,true ,false],
			 [true ,true ,true ,false,true ,true ,true ,true ,false,false,true ,false,false,false,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,false,false,true ,true ,false,false,true ,true ,true ,true ,false,true ,false,true ,false,true ,true ,false,false,true ,false,true ],
			 [true ,false,false,false,false,true ,false,false,false,false,false,true ,false,false,false,false,false,true ,true ,true ,false,false,false,false,true ,true ,false,true ,false,false,false,false,true ,false,false,true ,true ,false,true ,false,false,false,false,true ,true ,true ,false,false,true ],
			 [false,true ,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,true ,true ,true ,false,true ,true ,false,true ,true ,false,true ,false,true ,true ,false,false,true ,false,false,true ,false,true ,false,false,true ,true ,false,false,true ,true ,false,false,true ,false,false],
			 [true ,false,false,false,true ,false,false,false,false,true ,true ,false,true ,false,true ,false,false,false,true ,true ,true ,false,true ,false,false,true ,true ,false,false,true ,false,true ,true ,false,true ,false,false,true ,true ,false,false,false,true ,false,true ,true ,false,true ,true ],
			 [true ,false,false,false,false,true ,true ,true ,true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,false,true ,true ,false,true ,false,true ,false,false,false,false,false,false,true ,false,true ,true ,true ,true ,true ,false],
			 [false,false,false,false,true ,true ,false,true ,false,true ,true ,false,false,true ,true ,false,false,true ,true ,true ,true ,false,true ,false,false,false,false,true ,false,true ,true ,false,true ,true ,false,false,true ,false,true ,false,true ,false,false,false,true ,false,true ,true ,true ],
			 [true ,false,false,true ,false,false,true ,true ,true ,false,false,false,true ,false,true ,false,true ,false,true ,true ,true ,false,false,false,false,true ,false,false,false,false,true ,true ,false,true ,false,false,true ,false,false,true ,false,true ,false,true ,false,true ,false,false,true ],
			 [true ,true ,false,true ,false,true ,false,true ,false,false,true ,false,true ,false,true ,true ,false,false,false,false,true ,true ,false,true ,true ,false,false,false,true ,false,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,false,false],
			 [false,true ,false,false,true ,false,true ,false,false,true ,false,false,false,true ,true ,false,false,true ,false,false,false,false,false,false,false,false,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,false,false,false,false,false,true ,true ,true ,false,false,false,false,false],
			 [false,false,false,false,false,false,false,false,true ,false,false,false,false,true ,false,false,true ,false,true ,true ,false,false,false,false,false,false,true ,false,true ,true ,true ,true ,false,false,false,false,false,true ,false,false,false,true ,true ,false,true ,true ,false,true ,false],
			 [false,true ,false,false,true ,true ,true ,true ,true ,false,false,true ,false,true ,false,false,false,true ,false,false,true ,false,true ,true ,true ,true ,true ,false,false,true ,true ,false,false,false,true ,false,false,false,false,false,true ,true ,true ,true ,true ,true ,false,true ,false],
			 [true ,false,false,false,true ,false,false,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,true ,false,false,true ,false,false,false,true ,true ,true ,false,false,false,true ,false,true ,false,true ,true ,false,false,true ,false,false,false,true ,false,true ,false,false],
			 [false,true ,false,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,false,true ,false,true ,true ,false,true ,false,false,false,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ],
			 [false,true ,false,true ,true ,false,false,false,true ,false,true ,false,false,false,true ,true ,true ,false,true ,true ,false,false,true ,false,false,false,true ,true ,false,true ,false,false,true ,false,false,true ,false,true ,true ,false,true ,false,false,false,true ,true ,false,true ,true ],
			 [true ,false,false,false,true ,true ,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,false,false,false,true ,true ,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false],
			 [true ,false,true ,true ,false,false,false,true ,true ,true ,true ,true ,true ,false,false,false,false,false,true ,false,false,true ,true ,false,false,false,true ,false,true ,true ,true ,false,true ,false,false,true ,false,false,true ,false,false,false,false,true ,false,true ,false,false,true ],
			 [false,true ,false,false,true ,true ,true ,false,false,false,true ,false,false,true ,false,false,false,false,false,true ,true ,false,true ,true ,false,true ,false,false,false,false,false,true ,true ,false,true ,true ,false,true ,true ,false,true ,false,false,true ,false,true ,true ,true ,true ],
			 [true ,true ,false,false,true ,true ,false,true ,true ,true ,true ,true ,false,false,true ,true ,true ,true ,true ,true ,false,false,true ,true ,false,false,false,true ,true ,true ,false,true ,false,false,true ,false,false,true ,false,false,true ,false,false,true ,false,false,true ,true ,true ],
			 [false,true ,true ,false,true ,true ,true ,true ,true ,true ,false,false,true ,true ,true ,true ,false,true ,true ,true ,false,true ,true ,false,false,true ,false,false,false,false,false,true ,false,false,true ,false,false,true ,true ,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,true ,false,true ,true ,true ,false,false,true ,false,false,true ,true ,true ,false,true ,true ,true ,true ,false,true ,true ,false,false,false,true ,true ,false,false,true ,false,false,true ,false,false,true ,false,false,true ,true ,true ,false,true ,true ,true ,true ,false,false,true ],
			 [false,false,true ,false,true ,false,true ,true ,false,true ,true ,true ,true ,false,true ,true ,true ,true ,false,true ,false,true ,true ,false,false,true ,false,true ,false,true ,true ,false,true ,true ,false,true ,true ,false,true ,false,false,false,false,false,true ,false,false,false,false],
			 [true ,true ,false,true ,false,false,false,false,true ,false,true ,false,false,false,false,true ,true ,true ,true ,false,false,false,true ,true ,true ,false,false,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,true ,false,true ,true ,false,false,true ,false,true ,false],
			 [true ,true ,false,true ,true ,false,true ,false,false,false,true ,true ,true ,false,false,true ,true ,true ,false,false,true ,false,true ,false,false,false,false,true ,true ,false,true ,true ,false,true ,true ,false,true ,false,false,false,true ,false,false,false,false,false,true ,true ,false],
			 [true ,false,false,true ,true ,true ,false,false,true ,false,false,true ,false,true ,false,true ,true ,true ,false,false,false,false,true ,true ,false,false,false,true ,false,true ,false,true ,true ,true ,true ,false,true ,false,false,true ,true ,false,true ,false,false,false,true ,true ,true ],
			 [true ,true ,false,false,true ,false,true ,true ,true ,true ,false,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,true ,false,false,true ,false,true ,true ,true ,false,true ,true ,true ,true ,false,false,true ,false,true ,true ,false,true ,false,true ,true ,true ],
			 [false,true ,true ,true ,false,true ,false,false,false,false,false,false,false,true ,false,true ,true ,false,false,true ,true ,true ,false,true ,false,false,true ,false,false,true ,false,false,false,true ,false,false,true ,false,true ,false,false,false,false,true ,true ,true ,false,true ,true ],
			 [false,true ,false,false,false,true ,true ,true ,false,false,true ,false,false,false,true ,true ,false,false,true ,false,false,true ,true ,false,true ,false,false,false,true ,true ,true ,true ,false,false,false,true ,false,false,true ,true ,false,false,false,true ,true ,true ,true ,true ,false],
			 [false,true ,true ,true ,false,false,false,false,true ,false,false,false,true ,true ,false,true ,false,true ,false,false,false,false,true ,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ,false,false,false,false,false,true ,true ],
			 [true ,true ,true ,false,false,false,true ,false,false,false,false,true ,true ,false,true ,false,false,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,true ,false,true ,true ,false,true ,true ,true ,true ,true ,false,true ,true ,false],
			 [false,false,false,false,false,false,false,false,true ,true ,true ,true ,false,false,false,false,false,false,false,true ,false,true ,true ,false,false,false,true ,false,true ,false,false,false,true ,false,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,false,false,false,false,true ,false,true ,false,false,true ,false,false,true ,true ,true ,false,true ,false,true ,true ,true ,true ,true ,false,false,false,false,false,true ,true ,false,true ,true ,false,true ,false,true ,false,true ,false,true ],
			 [true ,false,false,false,false,false,true ,false,true ,false,true ,false,true ,true ,false,false,false,true ,true ,false,false,true ,true ,false,false,false,true ,true ,true ,false,false,true ,false,true ,false,true ,true ,false,true ,false,true ,false,false,false,true ,false,false,true ,false],
			 [true ,false,true ,true ,true ,false,true ,false,false,false,true ,true ,false,true ,false,false,false,false,true ,false,false,true ,true ,true ,true ,true ,true ,false,true ,false,false,true ,false,true ,true ,true ,false,true ,true ,false,true ,true ,true ,true ,true ,true ,false,false,false],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,true ,true ,true ,true ,false,false,false,true ,false,false,true ,false,false,false,false,true ,true ,false,false,false,true ,true ,false,true ,false,false,true ,false,false,false,true ,false,true ,false,true ,true ,false,false,false],
			 [true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ,true ,false,true ,false,false,true ,true ,true ,true ,true ,false,true ,false,false,true ,false,false,true ,false,true ,true ,true ,false,false,true ,false,false,false,false,false,true ,true ,false,false,false,false],
			 [true ,false,false,false,false,false,true ,false,true ,false,false,false,true ,false,false,false,false,false,true ,false,true ,false,true ,false,false,true ,false,true ,false,true ,false,false,true ,true ,true ,true ,true ,false,false,false,true ,true ,false,true ,false,false,true ,false,false],
			 [true ,true ,true ,true ,true ,true ,true ,false,false,false,true ,true ,true ,true ,false,true ,false,false,false,false,false,true ,true ,true ,true ,false,true ,true ,false,true ,true ,false,false,true ,false,false,true ,true ,false,true ,false,false,false,false,false,false,true ,true ,true ]])
		
		print(String(qr))
		
		
		qr = try QRCode("0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004", .L)
		XCTAssertEqualMultiarray(
			qr.modules,
			[[true ,true ,true ,true ,true ,true ,true ,false,false,false,false,true ,true ,true ,true ,false,false,true ,false,false,true ,true ,false,false,true ,true ,true ,false,false,false,true ,true ,true ,true ,true ,true ,true ],
			 [true ,false,false,false,false,false,true ,false,false,true ,true ,false,false,false,true ,false,true ,true ,true ,false,true ,false,true ,false,false,true ,false,false,true ,false,true ,false,false,false,false,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,false,false,false,false,true ,false,true ,true ,false,false,false,false,false,true ,true ,false,true ,false,true ,true ,true ,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,false,false,false,true ,true ,true ,false,false,true ,true ,false,false,true ,false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,true ,true ,false,false,false,false,true ,false,false,true ,false,true ,false,true ,false,true ,true ,false,true ,false,false,false,true ,false,true ,true ,true ,false,true ],
			 [true ,false,false,false,false,false,true ,false,false,false,false,true ,true ,false,false,false,false,false,true ,false,true ,false,true ,false,false,false,true ,false,false,false,true ,false,false,false,false,false,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,true ,true ,true ,true ,true ],
			 [false,false,false,false,false,false,false,false,false,false,true ,true ,false,false,false,false,true ,false,true ,true ,true ,false,true ,false,true ,false,true ,false,false,false,false,false,false,false,false,false,false],
			 [true ,true ,false,false,false,true ,true ,true ,false,true ,false,true ,false,true ,false,true ,false,true ,true ,false,true ,false,false,true ,false,true ,false,false,true ,false,false,false,true ,true ,false,false,false],
			 [true ,true ,true ,false,true ,true ,false,false,true ,true ,false,false,true ,false,false,true ,false,false,false,true ,true ,false,false,true ,true ,false,false,true ,true ,true ,false,false,true ,true ,true ,true ,false],
			 [true ,false,false,true ,true ,false,true ,false,true ,false,true ,false,false,false,true ,true ,false,true ,true ,false,true ,false,true ,false,false,false,false,true ,false,false,true ,true ,false,false,true ,false,true ],
			 [false,false,true ,true ,false,true ,false,false,false,false,true ,false,true ,false,true ,true ,false,false,false,true ,false,false,true ,false,true ,false,true ,false,true ,true ,true ,false,false,false,false,true ,true ],
			 [true ,true ,false,false,false,true ,true ,true ,true ,false,true ,true ,true ,false,true ,true ,true ,false,true ,true ,false,false,true ,true ,false,false,false,true ,false,true ,true ,false,false,false,false,true ,true ],
			 [true ,true ,true ,true ,false,false,false,true ,false,true ,false,false,false,true ,true ,true ,true ,false,false,true ,false,false,true ,true ,true ,false,false,true ,false,true ,false,false,false,true ,false,false,false],
			 [true ,true ,true ,true ,true ,false,true ,true ,true ,false,false,true ,true ,false,false,true ,false,false,true ,false,true ,true ,false,false,true ,false,false,true ,false,false,true ,false,false,false,false,true ,true ],
			 [false,true ,true ,false,true ,true ,false,true ,false,false,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,false,true ,false,false,false,true ,true ,false,true ,false,true ,true ,true ,true ,false],
			 [false,true ,true ,false,true ,true ,true ,true ,false,false,false,true ,false,true ,true ,true ,true ,true ,true ,false,false,false,true ,false,false,true ,false,true ,true ,false,true ,true ,true ,true ,true ,false,true ],
			 [true ,true ,true ,false,false,true ,false,false,false,true ,true ,false,true ,false,false,true ,false,false,false,true ,true ,false,false,true ,true ,false,true ,true ,false,true ,false,false,false,false,false,true ,false],
			 [true ,false,false,true ,false,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,true ,false,false,true ,true ,false,true ,false,true ,false,false,true ,true ,true ,true ,false,true ,true ],
			 [true ,true ,false,true ,false,true ,false,true ,false,false,true ,false,true ,false,false,true ,false,false,true ,false,false,false,false,true ,true ,false,true ,true ,false,true ,false,true ,false,false,false,false,false],
			 [true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,false,true ,true ,false,true ,false,true ,true ,false,false,false,true ,false,true ,true ,false,true ,false,true ,true ,false,true ,false,true ,true ,true ],
			 [false,false,false,false,false,false,false,true ,false,true ,false,false,false,false,false,true ,false,false,false,true ,false,false,true ,true ,false,false,false,true ,false,false,false,true ,true ,false,false,true ,false],
			 [true ,true ,false,true ,true ,false,true ,true ,true ,false,false,true ,true ,false,true ,true ,false,true ,false,false,false,false,false,false,true ,false,false,true ,false,true ,true ,true ,true ,true ,false,false,true ],
			 [false,false,true ,false,true ,false,false,true ,true ,false,true ,true ,false,false,true ,true ,true ,false,true ,true ,false,false,false,true ,false,false,false,false,true ,false,true ,true ,false,false,false,true ,false],
			 [false,true ,true ,true ,false,true ,true ,true ,true ,true ,true ,false,false,false,false,true ,true ,false,true ,true ,false,false,false,true ,true ,false,false,true ,false,true ,true ,false,false,false,false,true ,true ],
			 [true ,true ,false,true ,true ,false,false,false,true ,false,false,false,true ,false,false,true ,true ,false,false,true ,false,false,false,true ,false,false,false,true ,false,true ,false,false,false,true ,false,false,false],
			 [true ,false,true ,true ,false,false,true ,true ,false,false,true ,false,false,true ,true ,true ,true ,false,false,false,true ,true ,true ,false,true ,false,false,true ,true ,false,false,false,true ,true ,false,true ,true ],
			 [true ,false,false,true ,true ,false,false,true ,false,true ,false,false,true ,false,true ,true ,false,false,true ,false,true ,false,false,false,false,false,false,false,false,false,true ,true ,true ,false,true ,false,true ],
			 [true ,false,false,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,true ,false,true ,true ,true ,false,false,false,false,true ,false,false,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ],
			 [false,false,false,false,false,false,false,false,true ,true ,true ,false,false,false,true ,true ,false,false,true ,true ,true ,false,false,true ,true ,false,false,false,true ,false,false,false,true ,true ,false,true ,false],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,false,false,false,true ,true ,true ,true ,true ,true ,true ,true ,false,true ,false,true ,false,true ,true ,false,true ,false,true ,false,true ,false,true ,true ,true ],
			 [true ,false,false,false,false,false,true ,false,true ,true ,false,true ,false,false,false,false,true ,false,false,true ,false,false,true ,false,true ,false,true ,true ,true ,false,false,false,true ,true ,false,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,false,true ,false,true ,true ,true ,false,true ,true ,true ,false,false,true ,false,false,true ,false,true ,true ,true ,true ,true ,true ,true ,true ,true ,true ,false,true ],
			 [true ,false,true ,true ,true ,false,true ,false,false,true ,false,false,true ,false,false,true ,true ,false,true ,true ,true ,true ,false,true ,true ,false,true ,false,false,false,true ,false,false,true ,true ,false,false],
			 [true ,false,true ,true ,true ,false,true ,false,false,false,true ,false,true ,false,false,true ,false,false,false,false,false,true ,false,false,false,false,false,true ,false,true ,false,true ,false,false,false,true ,true ],
			 [true ,false,false,false,false,false,true ,false,true ,true ,false,false,false,false,false,true ,false,false,true ,false,false,false,true ,false,true ,false,true ,true ,true ,true ,true ,false,false,false,false,false,true ],
			 [true ,true ,true ,true ,true ,true ,true ,false,true ,false,false,true ,false,false,true ,true ,true ,false,false,false,false,false,true ,true ,true ,false,false,true ,true ,false,true ,false,true ,false,false,false,true ]])
		
		
		print(String(qr))
	}
}
